-- Example radiation data packet for an instrument with 2 detectors,1 gross
-- alpha counts and 1 gross beta counts, abbreviated "AB".
-- Packet quantities populated with arbitrary data for illustration.
-- Instrument transmits counts and count rate.
-- Instrument Status packet includes optional count rate.

grossABRadData RadiationData ::= {
  packetNumber 3,
  relativeTime 2.10,
  accumulationTime 1.0,
  detectorRadDataList {{detectorID 0, counts 1500, countRate 750.0},
                       {detectorID 1,counts 200, countRate 100}}
}

PacketType data ::= grossABRadData