-- Example instrument status packet for an instrument with 1 gamma
-- spectroscopic detector with compression, abbreviated "SGC" or "sgc".
-- Packet quantities populated with Co-57 measured with a ___ detector for ___ -- seconds for illustration.
-- Instrument transmits counts, count rate, exposure rate, and gamma spectrum.
-- Radiation Data packet includes gamma spectrum and optional count rate, 
-- exposure rate.

sgRadData RadiationData ::= {
    packetNumber 3,
    relativeTime 3.10,
    accumulationTime 2.0,
    detectorRadDataList {
                         {detectorID 0,
                          counts 1356,
                          countRate 678,
                          exposure 3.0,
                          gammaSpectrum {0, 1, 3, 31, 24, 19, 26, 28, 15, 12, 14, 15, 18, 23, 40, 30, 38, 38, 38, 100, 587, 8, 84, 18, 6, 4, 8, 7, 1, 4, 3, 3, 6, 4, 3, 3, 4, 3, 4, 0, 1, 2, 4, 3, 2, 1, 1, 2, 1, 1, 2, 1, 2, 0, 1, 2, 2, 0, 1, 2, 0, 1, 1, 2, 1, 0, 0, 0, 3, 1, 1, 0, 1, 1, 0, 1, 1, 2, 0, 1, 1, 0, 0, 0, 3, 2, 0, 7, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 3, 0, 4, 1, 1, 1, 0, 1, 1, 0, 6, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 2, 0, 5, 3, 1, 0, 1, 1, 0, 1, 1, 1, 0, 4, 1, 0, 11, 2, 0, 8, 1, 0, 22, 2, 0, 3, 1, 0, 2, 1, 1, 0, 1, 1, 0, 8, 3, 0, 4, 1, 0, 15, 1, 0, 11, 1, 2, 0, 10, 1, 0, 17}
                       }
    }
}

PacketType data ::= sgRadData