-- Example instrument status packet for an instrument with 1 gamma spectroscopic detector 
-- with compression.
-- Abbreviated "SGC" or "sgc".
-- Packet quantities populated with Co-57 measured with a ___ detector for ___ 
-- seconds for illustration.
-- Instrument transmits counts, count rate, exposure rate, and gamma spectrum.
-- Instrument Status packet includes optional battery status, detector voltage,
-- and detector temperature.
-- Spectrum compressed according to N42.42 CountedZero algorithm

sgInstrumentStatus InstrumentStatus ::= {
    instrumentStatusPacketNumber 2,
    timeInformationInstrumentStatus 
    {
            relativeTime 1050,
            timeStamp utc-DATE-TIME-FRACTIONAL : "2023-03-20T15:23:27.341Z"
    },
    instrumentStatusInformation
    {
        instrumentPower : instrumentPowerStatus TRUE,
        instrumentHealth TRUE,
        instrumentSelfCalibration TRUE
    },
    detectorsListInformationStatus
    {
        {
            detectorID 0,
            detectorGain "5204",
            detectorTemperature 25,
            detectorHealth TRUE
        }
    }
}

PacketType status ::= sgInstrumentStatus     