-- Example instrument status packet for an instrument with 1 gamma
-- spectroscopic detector with compression, abbreviated "SGC" or "sgc".
-- Packet quantities populated with Co-57 measured with a ___ detector for ___ -- seconds for illustration.
-- Instrument transmits counts, count rate, exposure rate, and gamma spectrum.
-- Radiation Data packet includes gamma spectrum and optional count rate, 
-- exposure rate.

sgRadData RadiationData ::= {
    radiationDataPacketNumber 1,
    timeInformationRadiationData
    {
        relativeTime 116011,
        accumulationTime 112911
    },
    detectorsListRadiationData {
        {
            detectorID 0,
            counts 273058,
            channelSpectrum {587, 9339, 13919, 6590, 6821, 7008, 7366, 7930, 
                            8137, 8014, 7964, 9313, 10812, 9506, 8446, 7484, 
                            6757, 6314, 5971, 5680, 5363, 5243, 5246, 5135, 
                            5099, 5166, 5433, 5577, 5703, 4835, 2862, 1793, 
                            1306, 900, 728, 615, 477, 510, 787, 3366, 14696, 
                            24910, 9902, 935, 214, 191, 161, 157, 171, 189, 
                            160, 169, 135, 144, 118, 115, 111, 110, 91, 89, 
                            86, 64, 38},
            derivedData
            {
                countRate 2744.299263,
                deadTime 6.375924139,
            }
        }
    }
}

PacketType data ::= sgRadData

