-- Example header packet for an instrument with 1 gamma spectroscopic detector.
-- Abbreviated "SG" or "sg".
-- Packet quantities populated with arbitrary data for illustration.
-- Instrument transmits counts, count rate, exposure rate, and gamma spectrum.
-- Header packet includes optional MCA channels, exposure coefficient,
-- calibration temperatures, and energy calibration.

sgHeader Header ::= {
    instrumentName "Example SG Detector",
    instrumentManufacturer "ANSI",
    instrumentModel "SG 1.00",
    instrumentSerial "SG-00000001",
    timeStampZero "20210201123015.0", -- 12:30:15 February 1 2021
    relativeTime 1,
    numDetectors 1,
    mcaChannels 256,
    detectorHeaderList {
                {detectorID 0,
                 detectorType 2,
                 exposureCoeff 7.5,
                 calibrationTemperatures {20, 40}, -- in Centigrade
                 energyCalibration {calibrationValues {
                                     {channel 45, energy 59.5}, -- 241Am at 20C
                                     {channel 605, energy 661.6}, -- 137Cs at 20C
                                     {channel 1310, energy 1331}}, -- 60Co at 20C
                                    calibrationValues {
                                     {channel 65, energy 59.5}, -- 241Am at 40C
                                     {channel 651, energy 661.6}, -- 137Cs at 40C
                                     {channel 1330, energy 1331}} -- 60Co at 40C
                                   }
                }
    }
}

PacketType headerpacket ::= sgHeader