-- Example footer packet for an instrument with 1 gamma
-- spectroscopic detector, abbreviated "SG" or "sg".
-- Packet quantities populated with arbitrary data for illustration.
-- Instrument transmits counts, count rate, exposure rate, and gamma spectrum.

sgFooter Footer ::= {
  relativeTime 180, -- 3 minutes
  timeStamp "20210201123315.0" -- 12:33:15 February 1 2021
}

PacketType footerpacket ::= sgFooter
