-- Example instrument status packet for an instrument with 1 gamma
-- spectroscopic detector, abbreviated "SG" or "sg".
-- Packet quantities populated with Co-60 measured with a ___ detector for ___ -- seconds for illustration.
-- Instrument transmits counts, count rate, exposure rate, and gamma spectrum.
-- Radiation Data packet includes gamma spectrum and optional count rate, 
-- exposure rate.

sgRadData RadiationData ::= {
    packetNumber 3,
    relativeTime 9.10,
    accumulationTime 9.0,
    detectorRadDataList {
                         {detectorID 0,
                          counts 1278,
                          countRate 159.75,
                          exposure 7.5,
                          gammaSpectrum {
                              173, 414, 1877, 7462, 9499, 4702, 3267, 3330, 
                              3357, 3415, 3476, 3521, 3499, 3738, 3815, 4014, 
                              4023, 4033, 4106, 4036, 3952, 3946, 4016, 4347, 
                              4966, 5525, 5287, 4859, 4745, 4410, 4130, 3977, 
                              3607, 3530, 3377, 3308, 3078, 3069, 2987, 2955, 
                              2834, 2849, 2692, 2578, 2645, 2598, 2634, 2612, 
                              2578, 2583, 2574, 2532, 2533, 2604, 2641, 2770, 
                              2743, 2813, 2734, 2904, 2821, 2529, 2104, 1513, 
                              1129, 940, 828, 706, 600, 503, 397, 369, 358, 
                              327, 305, 267, 224, 233, 271, 238, 378, 696, 
                              1402, 2864, 6134, 10663, 13131, 11003, 7169, 
                              2733, 743, 192, 122, 96, 105, 75, 89, 78, 78, 85, 
                              81, 84, 91, 96, 90, 85, 79, 99, 69, 56, 72, 79, 
                              65, 52, 66, 56, 55, 64, 51, 56, 61, 58, 41, 40, 
                              43, 55, 38, 33}
                       }
    }
}

PacketType data ::= sgRadData