-- Example footer packet for an instrument with 1 gamma
-- spectroscopic detector, abbreviated "SG" or "sg".
-- Packet quantities populated with arbitrary data for illustration.
-- Instrument transmits counts, count rate, exposure rate, and gamma spectrum.

sgFooter PacketType ::= footerpacket : {
   timeInformationFooter
    {
      relativeTime 18000,
      timeStamp utc-DATE-TIME-FRACTIONAL : "2023-03-20T15:23:29.341Z"
    },
    lastInstrumentStatusPacketNumber 2,
    lastRadiationDataPacketNumber 120
}