-- Example footer packet for an instrument with 1 gamma
-- spectroscopic detector, abbreviated "SG" or "sg".
-- Packet quantities populated with arbitrary data for illustration.
-- Instrument transmits counts, count rate, exposure rate, and gamma spectrum.

sgFooter Footer ::= {
   timeInformationFooter
    {
      relativeTime 3600
    },
    lastInstrumentStatusPacketNumber 1,
    lastRadiationDataPacketNumber 1,
    endFooterPacket 10101010
}

PacketType footerpacket ::= sgFooter
