-- Example instrument status packet for an instrument with 1 gamma
-- spectroscopic detector, abbreviated "SG" or "sg".
-- Packet quantities populated with arbitrary data for illustration.
-- Instrument transmits counts, count rate, exposure rate, and gamma spectrum.
-- Instrument Status packet includes optional battery status, detector voltage,
-- and detector temperature.

sgInstrumentStatus InstrumentStatus ::= {
    instrumentStatusPacketNumber 1,
    timeInformationInstrumentStatus
    {
        relativeTime 1200,
    },
    instrumentStatusInformation
    {
        instrumentTemperature 23,
        instrumentPower instrumentBatteryVoltage : 12.6,
        instrumentHealth TRUE,
        instrumentSelfCalibration TRUE
    },
    detectorsListInformationStatus 
    {
        {
            detectorID 0,
            detectorVoltage -1300.0,
            detectorGain "5204",
            detectorHealth TRUE
        }
    },
    endInstrumentStatusPacket 11001110
}

PacketType status ::= sgInstrumentStatus