-- Example instrument status packet for an instrument with 1 gamma
-- spectroscopic detector, abbreviated "SG" or "sg".
-- Packet quantities populated with arbitrary data for illustration.
-- Instrument transmits counts, count rate, exposure rate, and gamma spectrum.
-- Instrument Status packet includes optional battery status, detector voltage,
-- and detector temperature.

sgInstrumentStatus InstrumentStatus ::= {
    packetNumber 2,
    relativeTime 1.05,
    batteryStatus 75,
    detectorStatusList {{detectorID 0, detectorVoltage 1500,
    					           detectorTemperature 32}
    }
    }

PacketType status ::= sgInstrumentStatus