-- Example instrument status packet for an instrument with 1 gamma spectroscopic detector
-- with radionuclide identification (RIID), abbreviated "SGRIID" or "sgRIID".
-- Packet quantities populated with arbitrary data for illustration.
-- Instrument transmits counts, count rate, exposure rate, gamma spectrum,
-- and radionuclide identification and radionuclide confidence level.
-- Instrument Status packet includes optional battery status, detector voltage,
-- and detector temperature.
-- Identified radionuclides are denoted using 2 fields (bytes).
-- The first field (byte) identifies the element (Z), which ranges from 1 to 98.
-- The second field (byte) identifies the atomic mass (A), which ranges from 1
-- to 255. A detailed table is included in the standard.

streamedPacket StreamedPacket ::= instrumentStatus : {
    instrumentStatusPacketNumber 1,
    timeInformationInstrumentStatus
    {
        relativeTime 1200,
        timeStamp utc-DATE-TIME-FRACTIONAL : "2023-03-20T15:24:27.341Z"
    },
    instrumentStatusInformation
    {
        instrumentPower instrumentBatteryVoltage : 12.6,
        instrumentHealth TRUE,
        instrumentSelfCalibration TRUE
    },
    detectorsListInformationStatus 
    {
        {
            detectorID 0,
            detectorVoltage -1300.0,
            detectorGain 5204
        }
    }
}