-- Example radiation data packet for an instrument with 2 detectors,1 gross
-- gamma counts and 1 gross neutron counts, abbreviated "GN".
-- Packet quantities populated with arbitrary data for illustration.
-- Instrument transmits counts, count rate, and exposure rate.

streamedPacket StreamedPacket ::= footer : {
  timeInformationFooter
  {
      relativeTime 197412,
      timeStamp utc-DATE-TIME-FRACTIONAL : "2023-05-04T13:12:00.341Z"
  },
  lastRadiationDataPacketNumber 55
}