-- Example radiation data packet for an instrument with 2 detectors,1 gross
-- gamma counts and 1 gross neutron counts, abbreviated "GN".
-- Packet quantities populated with arbitrary data for illustration.
-- Instrument transmits counts, count rate, and exposure rate.
-- Instrument Status packet includes optional count rate and exposure rate.

streamedPacket StreamedPacket ::= radiationData : {
  radiationDataPacketNumber 55,
  timeInformationRadiationData
  {
    relativeTime 163662,
    accumulationTime 1000
    instrumentLocation
    {
      latitude 37.916049, 
      longitude -122.338089,
      elevation 1.29
    }
  },
  detectorsListRadiationData
  {
    {
      detectorID 0,
      counts 39,
      derivedData
        {
          countRate 55.9,
          alarm1 TRUE,
          alarm2 FALSE
        }
    },
    {
      detectorID 1,
      counts 113,
      derivedData
        {
          countRate 140.6,
          dose 0.0004526,
          doseRate 2.027,
          alarm1 TRUE,
          alarm2 TRUE,
          deadTime 0.00437
        }
    }
  }
}