-- Example radiation data packet for an instrument with 2 detectors,1 gross
-- gamma counts and 1 gross neutron counts, abbreviated "GN".
-- Packet quantities populated with arbitrary data for illustration.
-- Instrument transmits counts, count rate, and exposure rate.

grossGNfooter Footer ::= {
  timeInformationFooter
  {
      relativeTime 600000,
      timeStamp utc-DATE-TIME-FRACTIONAL : "2023-03-20T15:33:27.341Z",
  },
  lastRadiationDataPacketNumber 3,
  endFooterPacket 01010101,
}

PacketType footerpacket ::= grossGNfooter