streamedPacket PacketType ::= data : {
  radiationDataPacketNumber 3,
  timeInformationRadiationData
  {
    relativeTime 3010,
    accumulationTime 2000
  },
  detectorsListRadiationData
  {
    {
      detectorID 0,
      counts 6489,
      derivedData
        {
          countRate 3244.5,
          exposure 40.056,
          exposureRate 72100.0,
          alarm1 = TRUE,
          deadTime = 10.0,
          liveTime = 1800.0
        }
    }
  },
  endRadiationDataPacket 1110010
}

-- Updated 03/28/2023