streamedPacket PacketType ::= status : {
  instrumentStatusPacketNumber 2,
  timeInformationInstrumentStatus {
    relativeTime 1005,
    timeStamp utc-DATE-TIME-FRACTIONAL : "2023-03-20T15:23:27.341Z" },
  instrumentStatusInformation {
    instrumentTemperature 23,
    instrumentPower instrumentBatteryRemainingCharge : 70,
    instrumentHealth TRUE },
  detectorsListInformationStatus
  {
    {
      detectorID 0,
      detectorVoltage = -1290,
      detectorTemperature = 34
    }
  },
  endInstrumentStatusPacket 1111000
}

-- Updated 03/28/2023
-- Example instrument status packet for a simple gross gamma counts
-- instrument with 1 detector.
-- Packet quantities populated with arbitrary data for illustration.
-- Instrument transmits counts, count rate, and exposure rate.
-- Instrument Status packet includes optional battery status,
-- and detector temperature.