-- Example radiation data packet for a simple gross gamma counts instrument
-- with 1 detector.
-- Packet quantities populated with arbitrary data for illustration.
-- Instrument tranmits counts, count rate, and exposure rate.
-- Radiation data packet includes optional count rate and exposure rate.

streamedPacket PacketType ::= data : {
  radiationDataPacketNumber 3,
  timeInformationRadiationData
  {
    relativeTime 210,
    accumulationTime 1000,
    timeStamp utc-DATE-TIME-FRACTIONAL : "2022-07-12T09:49:01.649Z"
  },
  detectorsListRadiationData
  {
    {
      detectorID 0,
      counts 1500,
      derivedData
        {
          countRate 750.0,
          exposureRate 7.5
        }
    }
  }
}